[build-system]
requires = [
    "setuptools >= 65",
    "wheel >= 0.38",
    "pyinstaller"
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
py-modules = []

[project]
name = "ftdi-cloner"
version = "0.1.0"
dependencies = [
    "ftd2xx>=1.3.8",
    "simple-hexdump",
    "pyinstaller"
]
